// Self-serve API documentation (#33): one hand-curated reference object plus
// two dependency-free express handlers that serve it.
//
//   GET /api-docs.json  -> apiDocsJsonHandler  raw JSON dump (public)
//   GET /api-docs       -> apiDocsPageHandler  searchable HTML viewer (public)
//
// The endpoint list below is CURATED BY HAND, deliberately not generated by
// reflecting over the express route table: descriptions carry product context
// (which params matter, which rules apply) that no router walk could infer,
// and the shape stays stable regardless of how routes are mounted. It must be
// re-touched when notable endpoints are added — tests/api-docs.test.js pins
// only structural invariants (valid method/path/auth/summary per entry,
// unique method+path pairs, JSON round-trip, version stamp), not content.
//
// auth vocabulary: 'public' | 'customer' | 'salon' | 'staff' | 'admin' |
// 'any-auth' (any valid token), joined with '+' for multi-role guards
// (e.g. 'salon+staff') so every entry states exactly who may call it.
// params: optional array of one-liners for NOTABLE query/body parameters.

const pkg = require('../package.json');

const apiDocs = {
  openapi: '3.0.3',
  info: {
    title: 'Fresha Salon App API',
    version: pkg.version,
    description:
      'Salon booking platform: customers browse salons and book paid appointments, salon owners run services/staff/promos/analytics, staff see their day, admins watch the platform. All endpoints live under /api (legacy /api/buisness mirrors /api/business). Listings accept an optional page/limit envelope everywhere.',
  },
  servers: [{ url: '/', description: 'Same origin as the SPA' }],
  tags: [
    'Meta',
    'Health',
    'Auth',
    'Account',
    'Favorites',
    'Browse',
    'Appointments',
    'Payments',
    'Waitlist',
    'Notifications',
    'Loyalty & Referrals',
    'Salon Console',
    'Analytics',
    'Staff',
    'Admin',
  ],
  endpoints: [
    // ── Meta ────────────────────────────────────────────────────────────
    { method: 'GET', path: '/api-docs', summary: 'This reference as a searchable HTML viewer.', auth: 'public', tag: 'Meta' },
    { method: 'GET', path: '/api-docs.json', summary: 'This reference as raw JSON.', auth: 'public', tag: 'Meta' },

    // ── Health ──────────────────────────────────────────────────────────
    { method: 'GET', path: '/health', summary: 'Lightweight liveness probe; no DB dependency.', auth: 'public', tag: 'Health' },
    { method: 'GET', path: '/health/deep', summary: 'DB ping + uptime/memory; 503 when degraded.', auth: 'public', tag: 'Health' },

    // ── Auth ────────────────────────────────────────────────────────────
    { method: 'POST', path: '/api/user/signup', summary: 'Create customer account.', auth: 'public', tag: 'Auth', params: ['referralCode — optional; credits +100 points to both sides (#28)'] },
    { method: 'POST', path: '/api/user/login', summary: 'Customer login; returns JWT with role claim.', auth: 'public', tag: 'Auth' },
    { method: 'POST', path: '/api/business/signup', summary: 'Create salon account.', auth: 'public', tag: 'Auth' },
    { method: 'POST', path: '/api/business/login', summary: 'Salon owner login.', auth: 'public', tag: 'Auth' },
    { method: 'POST', path: '/api/staff/login', summary: 'Staff login.', auth: 'public', tag: 'Auth' },
    { method: 'POST', path: '/api/admin/login', summary: 'Admin login (timing-safe compare).', auth: 'public', tag: 'Auth' },
    { method: 'POST', path: '/api/user/forgot-password', summary: 'Emails a hashed one-time reset token (60-min window).', auth: 'public', tag: 'Auth', params: ['email'] },
    { method: 'POST', path: '/api/user/reset-password', summary: 'Consumes token, rotates password; identical response either way.', auth: 'public', tag: 'Auth', params: ['email', 'token', 'newPassword (min 8)'] },
    { method: 'POST', path: '/api/user/verify-email', summary: 'Burns email verification token.', auth: 'public', tag: 'Auth', params: ['email', 'token'] },
    { method: 'POST', path: '/api/user/resend-verification', summary: 'Rotates + resends token; always a generic 200.', auth: 'public', tag: 'Auth', params: ['email'] },

    // ── Account ─────────────────────────────────────────────────────────
    { method: 'GET', path: '/api/user/profile', summary: "Caller's own profile.", auth: 'any-auth', tag: 'Account' },
    { method: 'PUT', path: '/api/user/edit', summary: 'Update own profile fields.', auth: 'any-auth', tag: 'Account' },
    { method: 'DELETE', path: '/api/user/me', summary: 'GDPR self-deletion: re-auths by password, cancels future bookings, anonymizes the row (#32).', auth: 'customer', tag: 'Account', params: ['body password — required; wrong password 401 with zero writes'] },
    { method: 'GET', path: '/api/user/search', summary: 'Enumerate users by name/email substring.', auth: 'admin', tag: 'Account', params: ['q'] },

    // ── Recently Viewed (#58) ───────────────────────────────────────────
    { method: 'GET', path: '/api/user/recently-viewed', summary: 'Own recently-viewed salons, most recent first, one row per salon (re-viewing bumps it to the top).', auth: 'customer', tag: 'Account', params: ['limit? — 1..20, default 8; out-of-range values clamp rather than 400'] },
    { method: 'POST', path: '/api/user/recently-viewed', summary: 'Record a salon view (upsert + bump); inactive salons are ignored, never 404.', auth: 'customer', tag: 'Account', params: ['salonId — required'] },

    // ── Favorites ───────────────────────────────────────────────────────
    { method: 'GET', path: '/api/user/favorites', summary: 'Own favorite salons, newest-first.', auth: 'any-auth', tag: 'Favorites', params: ['page, limit — either present switches to the { data, total } envelope'] },
    { method: 'POST', path: '/api/user/favorites', summary: 'Favorite a salon (idempotent).', auth: 'any-auth', tag: 'Favorites', params: ['body salonId'] },
    { method: 'DELETE', path: '/api/user/favorites/:salonId', summary: 'Un-favorite (404 if never added).', auth: 'any-auth', tag: 'Favorites' },

    // ── Favorite Staff (#59) ────────────────────────────────────────────
    { method: 'GET', path: '/api/user/favorites/staff', summary: 'Own favorite stylists with the salon/service context they were picked in, newest-first.', auth: 'customer', tag: 'Favorites' },
    { method: 'POST', path: '/api/user/favorites/staff', summary: 'Favorite a stylist (idempotent); 404 for an inactive stylist or a salon/service mismatch.', auth: 'customer', tag: 'Favorites', params: ['staffId — required; must be active and offer serviceId at salonId', 'salonId, serviceId? — the context the customer chose them in'] },
    { method: 'DELETE', path: '/api/user/favorites/staff/:staffId', summary: 'Un-favorite a stylist; forgiving 200 even when it was never added.', auth: 'customer', tag: 'Favorites' },

    // ── Browse (public) ─────────────────────────────────────────────────
    { method: 'GET', path: '/api/business/getall', summary: 'Browse salons with search/filter/sort (#22); optional token adds isFavorite.', auth: 'public', tag: 'Browse', params: ['search — case-insensitive name/address substring', 'category — active-service category filter', 'minRating — average rating floor', 'sort — rating | price-low | price-high | newest | name', 'page, limit — envelope switch'] },
    { method: 'GET', path: '/api/business/getsalonbyId', summary: 'One salon detail by id.', auth: 'public', tag: 'Browse', params: ['salonId'] },
    { method: 'GET', path: '/api/business/profile/:salonId', summary: 'Public profile with reviews (+ owner replies) and gallery images.', auth: 'public', tag: 'Browse' },
    { method: 'GET', path: '/api/business/staff', summary: 'Public staff directory with each member\'s bookable services (#15).', auth: 'public', tag: 'Browse', params: ['salonId'] },
    { method: 'GET', path: '/api/userdashboard/getAllActiveServicesBySalonId', summary: "A salon's active service catalog.", auth: 'public', tag: 'Browse', params: ['salonId'] },

    // ── Appointments ────────────────────────────────────────────────────
    { method: 'POST', path: '/api/appointment/check', summary: 'Availability check: free staff for a slot + configured slot step (#12).', auth: 'customer', tag: 'Appointments', params: ['salonId, serviceId, staffId?, dateSelect (YYYY-MM-DD), time (HH:mm)'] },
    { method: 'GET', path: '/api/appointment/getAll', summary: "Customer's own bookings, newest-first (#57).", auth: 'customer', tag: 'Appointments', params: ['page, limit — envelope switch', 'status? — one of the booking statuses; invalid values 400', 'from, to? — YYYY-MM-DD inclusive bounds; inverted ranges 400', 'salonId? — restrict to one salon'] },
    { method: 'GET', path: '/api/appointment/upcoming', summary: 'Next ≤5 pending/confirmed bookings starting in the future, soonest-first (#29).', auth: 'customer', tag: 'Appointments' },
    { method: 'POST', path: '/api/appointment/quote', summary: 'Pre-payment total in minor units: service price, promo discount, tip and group size (#56).', auth: 'customer', tag: 'Appointments', params: ['serviceId — required; archived services are refused', 'promoCode? — validated against the same rules as checkout', 'tipAmount? — added AFTER the discount, never discounted', 'partySize? — 1..20, default 1'] },
    { method: 'POST', path: '/api/appointment/:appointmentId/rebook', summary: 'One-tap rebook of a past booking: the next bookable slot for the same service (#55). Returns a checkout payload, NOT a booking.', auth: 'customer', tag: 'Appointments', params: ['horizonDays? — 1..60, default 14', 'staffId? — prefer a specific stylist', 'preferSameTime? — default true; nearest to the original time of day rather than earliest free', '409 NOT_REBOOKABLE on a live booking — that is what reschedule is for'] },

    // ── Recurring Series (#61) ──────────────────────────────────────────
    { method: 'POST', path: '/api/appointment/series', summary: 'Create a recurring booking series; occurrences are materialized by a sweep, not all at once.', auth: 'customer', tag: 'Appointments', params: ['salonId, serviceId, startDate (today or later), time', 'frequency — weekly | biweekly | monthly', 'totalVisits — 2..52', 'staffId? — falls through to a free colleague when unavailable'] },
    { method: 'GET', path: '/api/appointment/series', summary: "Caller's own series with progress and the next due date.", auth: 'customer', tag: 'Appointments' },
    { method: 'PATCH', path: '/api/appointment/series/:id', summary: 'Pause, resume or cancel own series; cancelled is terminal and keeps past occurrences.', auth: 'customer', tag: 'Appointments', params: ['status — active | paused | cancelled'] },

    { method: 'PATCH', path: '/api/appointment/:appointmentId/reschedule', summary: 'Move own booking (>24 h out); slot revalidated against hours/conflicts (#6).', auth: 'customer', tag: 'Appointments', params: ['dateSelect, time', 'staffId? — reassign within same salon/service', 'customerNote? — non-empty overwrites, empty clears', 'partySize? — 1..20; omitted leaves headcount untouched'] },
    { method: 'PUT', path: '/api/appointment/cancel/:appointmentId', summary: 'Owner cancels own booking (>24 h free window), optionally with a reason (#60).', auth: 'any-auth', tag: 'Appointments', params: ['cancellationReason? — fixed vocabulary; absent keeps the pre-#60 behaviour byte-identical', 'cancellationNote? — free text, max 200 chars, ignored without a reason'] },
    { method: 'PUT', path: '/api/appointment/status/:appointmentId', summary: 'Accept/decline/complete/no-show workflow; no-show is terminal, past-only, salon-only (#13).', auth: 'salon+staff', tag: 'Appointments', params: ['status'] },
    { method: 'GET', path: '/api/appointment/sceduledAppointments', summary: "Salon's scheduled appointments calendar view.", auth: 'salon', tag: 'Appointments', params: ['page, limit — envelope switch'] },
    { method: 'GET', path: '/api/appointment/export/csv', summary: 'Full booking ledger as RFC-4180 CSV attachment (#9).', auth: 'salon', tag: 'Appointments', params: ['from, to? — YYYY-MM-DD bounds, from <= to'] },
    { method: 'POST', path: '/api/appointment/mail', summary: 'Email a booking confirmation.', auth: 'customer', tag: 'Appointments' },
    { method: 'PUT', path: '/api/appointment/review/:appointmentId', summary: 'Rate/review a completed booking.', auth: 'customer', tag: 'Appointments', params: ['rating', 'userReview'] },
    { method: 'PUT', path: '/api/appointment/staffreview/:appointmentId', summary: "Staff/salon note on an appointment.", auth: 'staff+salon', tag: 'Appointments' },
    { method: 'PUT', path: '/api/appointment/:appointmentId/reply', summary: 'Salon publicly replies to a review (upsert; only after it exists) (#8).', auth: 'salon', tag: 'Appointments', params: ['reply — 1..1000 chars'] },

    // ── Payments ────────────────────────────────────────────────────────
    { method: 'POST', path: '/api/pay', summary: 'Create a Cashfree order for a booking; price resolved server-side.', auth: 'customer', tag: 'Payments', params: ['promoCode? — validated after authoritative price lookup (#10)', 'customerNote? — free-text note carried onto the booking, max 500 (#23)', 'partySize — 1..20, default 1; one pro serves the group (#25)', 'tipAmount? — 0..10000, rounded to 2dp, added AFTER discount (#26)'] },
    { method: 'GET', path: '/api/pay/stuck', summary: "Caller's paid orders with no booking yet (webhook-miss recovery).", auth: 'customer', tag: 'Payments' },
    { method: 'POST', path: '/api/pay/webhook', summary: 'Cashfree webhook; signature verified over the raw body, idempotent finalize.', auth: 'public', tag: 'Payments' },
    { method: 'GET', path: '/api/pay/:orderId', summary: 'Payment status; stakeholders only, triggers idempotent booking finalize on read (#1).', auth: 'customer+salon+admin', tag: 'Payments' },

    // ── Waitlist (#30) ──────────────────────────────────────────────────
    { method: 'POST', path: '/api/appointment/waitlist', summary: 'Join a salon queue for a DATE; 409 when already actively waiting.', auth: 'customer', tag: 'Waitlist', params: ['salonId', 'date — YYYY-MM-DD, today or later', 'partySize — 1..20, default 1'] },
    { method: 'GET', path: '/api/appointment/waitlist', summary: 'My waitlist entries newest-first.', auth: 'customer', tag: 'Waitlist', params: ['page, limit — envelope switch'] },
    { method: 'DELETE', path: '/api/appointment/waitlist/:id', summary: 'Soft-leave (status=left); foreign ids 404.', auth: 'customer', tag: 'Waitlist' },
    { method: 'GET', path: '/api/salonsdashboard/waitlist', summary: "Salon's day sheet: who is queued for a date, oldest-first.", auth: 'salon', tag: 'Waitlist', params: ['date — required YYYY-MM-DD'] },

    // ── Notifications ───────────────────────────────────────────────────
    { method: 'GET', path: '/api/notifications', summary: 'Own notifications newest-first (role decides the mailbox).', auth: 'customer+salon+admin', tag: 'Notifications', params: ['page, limit — envelope switch'] },
    { method: 'PATCH', path: '/api/notifications/:id/read', summary: 'Mark one read (404 for other mailboxes).', auth: 'customer+salon+admin', tag: 'Notifications' },
    { method: 'POST', path: '/api/notifications/read-all', summary: 'Mark all own notifications read.', auth: 'customer+salon+admin', tag: 'Notifications' },

    // ── Loyalty & Referrals ─────────────────────────────────────────────
    { method: 'GET', path: '/api/user/loyalty', summary: 'Points balance + lifetime earned; 10 points per completed booking (#27).', auth: 'customer', tag: 'Loyalty & Referrals' },
    { method: 'GET', path: '/api/user/referral', summary: 'Personal referral code, lazily assigned on first read (#28).', auth: 'customer', tag: 'Loyalty & Referrals' },

    // ── Salon Console (all token-scoped to req.user.salonId) ───────────
    { method: 'GET', path: '/api/business/getsalonbyIdSalonId', summary: "Owner's own salon record.", auth: 'salon', tag: 'Salon Console' },
    { method: 'PUT', path: '/api/business/changeSalonDetail', summary: 'Update own salon details.', auth: 'salon', tag: 'Salon Console' },
    { method: 'POST', path: '/api/salonsdashboard/services/add', summary: 'Create a service (price/duration/category).', auth: 'salon', tag: 'Salon Console' },
    { method: 'GET', path: '/api/salonsdashboard/services/getall', summary: 'Own services including inactive.', auth: 'salon', tag: 'Salon Console' },
    { method: 'GET', path: '/api/salonsdashboard/services/get/:id', summary: 'One own service.', auth: 'salon', tag: 'Salon Console' },
    { method: 'PUT', path: '/api/salonsdashboard/services/update/:id', summary: 'Edit own service.', auth: 'salon', tag: 'Salon Console' },
    { method: 'DELETE', path: '/api/salonsdashboard/services/delete/:id', summary: 'Delete own service.', auth: 'salon', tag: 'Salon Console' },
    { method: 'POST', path: '/api/salonsdashboard/staff/add', summary: 'Add a staff member.', auth: 'salon', tag: 'Salon Console' },
    { method: 'GET', path: '/api/salonsdashboard/staff/getallstaff', summary: 'Own roster.', auth: 'salon', tag: 'Salon Console' },
    { method: 'GET', path: '/api/salonsdashboard/staff/getStaff', summary: 'One own staff member.', auth: 'salon', tag: 'Salon Console' },
    { method: 'PUT', path: '/api/salonsdashboard/staff/assignServices', summary: 'Set which services a staff member provides.', auth: 'salon', tag: 'Salon Console' },
    { method: 'PUT', path: '/api/salonsdashboard/staff/updateStatus', summary: 'Activate/deactivate a staff member.', auth: 'salon', tag: 'Salon Console' },
    { method: 'POST', path: '/api/salonsdashboard/staff/blockouts', summary: 'Block out unbookable time for a staff member.', auth: 'salon', tag: 'Salon Console' },
    { method: 'GET', path: '/api/salonsdashboard/staff/blockouts', summary: 'List blockouts.', auth: 'salon', tag: 'Salon Console' },
    { method: 'DELETE', path: '/api/salonsdashboard/staff/blockouts/:id', summary: 'Remove a blockout.', auth: 'salon', tag: 'Salon Console' },
    { method: 'PUT', path: '/api/salonsdashboard/gallery', summary: 'Upsert up to 10 gallery image URLs (#11).', auth: 'salon', tag: 'Salon Console', params: ['images — http(s) URLs; empty array clears'] },
    { method: 'GET', path: '/api/salonsdashboard/booking-config', summary: 'Booking lead time + slot grid policy (#12).', auth: 'salon', tag: 'Salon Console' },
    { method: 'PUT', path: '/api/salonsdashboard/booking-config', summary: 'Replace lead time (0–7 days) + slot step (10–60 min or null).', auth: 'salon', tag: 'Salon Console' },
    { method: 'GET', path: '/api/salonsdashboard/hours', summary: 'Effective per-day weekly schedule: stored overrides merged over legacy defaults (#24).', auth: 'salon', tag: 'Salon Console' },
    { method: 'PUT', path: '/api/salonsdashboard/hours', summary: 'Replace the whole weekly schedule (all 7 days required).', auth: 'salon', tag: 'Salon Console', params: ['weeklyHours — keyed 0..6, each { open, close, closed }; closed days ignore times'] },
    { method: 'POST', path: '/api/salonsdashboard/promos', summary: 'Create a discount code (percent/flat, caps, window, usage limit) (#10).', auth: 'salon', tag: 'Salon Console' },
    { method: 'GET', path: '/api/salonsdashboard/promos', summary: 'Own promo codes incl. usage counts.', auth: 'salon', tag: 'Salon Console' },
    { method: 'PATCH', path: '/api/salonsdashboard/promos/:id', summary: 'Toggle/edit a promo (code/type immutable).', auth: 'salon', tag: 'Salon Console' },
    { method: 'DELETE', path: '/api/salonsdashboard/promos/:id', summary: 'Soft delete: isActive=false, row kept for audit.', auth: 'salon', tag: 'Salon Console' },

    // ── Analytics ───────────────────────────────────────────────────────
    { method: 'GET', path: '/api/salonsdashboard/analytics', summary: 'Legacy KPI aggregation (ratings, revenue snapshot).', auth: 'any-auth', tag: 'Analytics' },
    { method: 'GET', path: '/api/salonsdashboard/calendar', summary: 'Calendar-view aggregation of scheduled appointments.', auth: 'any-auth', tag: 'Analytics' },
    { method: 'GET', path: '/api/salonsdashboard/analytics/revenue', summary: 'Daily revenue/tips/discounts/bookings series + totals, dense zero days (#31).', auth: 'salon', tag: 'Analytics', params: ['days — clamped 1..90, default 30'] },
    { method: 'GET', path: '/api/salonsdashboard/analytics/top-services', summary: 'Top 5 completed services by booking count in the window (#31).', auth: 'salon', tag: 'Analytics', params: ['days — clamped 1..90, default 30'] },
    { method: 'GET', path: '/api/salonsdashboard/analytics/cancellation-reasons', summary: 'Cancellation counts grouped by reason, with an explicit bucket for pre-#60 / unreported ones.', auth: 'salon', tag: 'Analytics', params: ['days — clamped 1..90, default 30'] },

    // ── Staff ───────────────────────────────────────────────────────────
    { method: 'GET', path: '/api/staff/today', summary: "Signed-in staff member's today appointments, time ASC (#13).", auth: 'staff', tag: 'Staff' },
    { method: 'GET', path: '/api/staff/appointments', summary: "Staff member's appointments, scoped to their own id.", auth: 'staff', tag: 'Staff' },

    // ── Admin ───────────────────────────────────────────────────────────
    { method: 'GET', path: '/api/admin/stats', summary: 'Platform totals, status breakdown, success-only revenue + tips, 7-day signups (#16/#26).', auth: 'admin', tag: 'Admin' },
    { method: 'GET', path: '/api/admin/audit', summary: 'Append-only audit trail of admin deletions (#16).', auth: 'admin', tag: 'Admin', params: ['page, limit — envelope switch'] },
    { method: 'GET', path: '/api/admin/appointments/getall', summary: 'All platform appointments.', auth: 'admin', tag: 'Admin', params: ['page, limit — envelope switch'] },
    { method: 'DELETE', path: '/api/admin/appointments/:id', summary: 'Delete an appointment (audited).', auth: 'admin', tag: 'Admin' },
    { method: 'DELETE', path: '/api/admin/users/:id', summary: 'Delete a user account (audited).', auth: 'admin', tag: 'Admin' },
  ],
};

// ── HTML viewer ───────────────────────────────────────────────────────
// Single self-contained template literal: inline CSS only, no external
// CDNs/scripts/fonts (helmet-CSP friendly), dark mode via prefers-color-scheme.
// Client-side filter matches substrings of method+path+summary; entries are
// grouped under their section heading.
const docsHtmlPage = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Fresha Salon App API</title>
<style>
  :root { color-scheme: light dark;
    --bg: #fafafa; --fg: #18181b; --muted: #71717a; --border: #e4e4e7;
    --card: #ffffff; --accent: #2563eb; }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #101012; --fg: #e4e4e7; --muted: #8b8b94; --border: #2c2c31;
      --card: #1a1a1f; --accent: #60a5fa; }
  }
  * { box-sizing: border-box; }
  body { margin: 0 auto; padding: 1.25rem; max-width: 60rem;
    font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
    background: var(--bg); color: var(--fg); }
  h1 { font-size: 1.35rem; margin: 0 0 .25rem; }
  .sub { color: var(--muted); font-size: .85rem; margin: 0 0 1rem; }
  #filter { width: 100%; padding: .55rem .75rem; font-size: 1rem;
    border: 1px solid var(--border); border-radius: .5rem;
    background: var(--card); color: var(--fg); margin-bottom: 1.25rem; }
  h2 { font-size: .95rem; margin: 1.5rem 0 .4rem; }
  h2 .count { color: var(--muted); font-weight: 400; font-size: .78rem; }
  .row { display: flex; flex-wrap: wrap; gap: .45rem; align-items: baseline;
    padding: .4rem 0; border-bottom: 1px solid var(--border); }
  .method { font-weight: 700; font-size: .68rem; letter-spacing: .04em;
    padding: .14rem .45rem; border-radius: .3rem; color: #fff; flex: none; }
  .m-get { background: #2563eb; } .m-post { background: #16a34a; }
  .m-put { background: #d97706; } .m-patch { background: #7c3aed; }
  .m-delete { background: #dc2626; }
  .path { font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: .84rem; word-break: break-all; }
  .auth { font-size: .66rem; color: var(--muted); border: 1px solid var(--border);
    border-radius: 999px; padding: .05rem .5rem; flex: none; white-space: nowrap; }
  .summary { font-size: .82rem; color: var(--muted); flex-basis: 100%;
    padding-left: .15rem; }
  ul.params { margin: -.2rem 0 .5rem; padding-left: 1.4rem;
    font-size: .76rem; color: var(--muted); flex-basis: 100%; }
  .err { color: #dc2626; font-size: .85rem; }
</style>
</head>
<body>
<h1>Fresha Salon App API</h1>
<p class="sub">Hand-curated reference &middot; version served in /api-docs.json &middot; type to filter</p>
<input id="filter" type="search" placeholder="Filter by path or summary&hellip;" autocomplete="off" autofocus>
<div id="out">Loading&hellip;</div>
<script>
(async () => {
  const esc = (s) => String(s).replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  try {
    const d = await (await fetch('/api-docs.json')).json();
    const groups = new Map();
    for (const e of d.endpoints) {
      if (!groups.has(e.tag)) groups.set(e.tag, []);
      groups.get(e.tag).push(e);
    }
    const out = document.getElementById('out');
    const q = document.getElementById('filter');
    const render = () => {
      const term = q.value.trim().toLowerCase();
      let html = '';
      for (const [tag, list] of groups) {
        const rows = list.filter((e) => !term ||
          (e.method + ' ' + e.path + ' ' + e.summary).toLowerCase().includes(term));
        if (!rows.length) continue;
        html += '<h2>' + esc(tag) + ' <span class="count">(' + rows.length + ')</span></h2>';
        for (const e of rows) {
          html += '<div class="row">'
            + '<span class="method m-' + esc(e.method.toLowerCase()) + '">' + esc(e.method) + '</span>'
            + '<span class="path">' + esc(e.path) + '</span>'
            + '<span class="auth">' + esc(e.auth) + '</span>'
            + '<span class="summary">' + esc(e.summary) + '</span>';
          if (e.params && e.params.length) {
            html += '<ul class="params">'
              + e.params.map((p) => '<li>' + esc(p) + '</li>').join('') + '</ul>';
          }
          html += '</div>';
        }
      }
      out.innerHTML = html || '<p class="err">No matching endpoints.</p>';
    };
    q.addEventListener('input', render);
    render();
  } catch (err) {
    document.getElementById('out').innerHTML =
      '<p class="err">Failed to load API docs: ' + esc(err.message) + '</p>';
  }
})();
</script>
</body>
</html>`;

// ── Route handlers (exported so app.js mounts them AND tests can drive
// them directly with mock req/res — app.js itself starts a listener on
// require, so it can never be imported from a test suite) ─────────────

function apiDocsJsonHandler(_req, res) {
  res.status(200).json(apiDocs);
}

function apiDocsPageHandler(_req, res) {
  res.status(200).type('html').send(docsHtmlPage);
}

module.exports = { apiDocs, docsHtmlPage, apiDocsJsonHandler, apiDocsPageHandler };
